### ISSUE TITLE
ES6 Support

### ISSUE THREAD

**Issue by keawade** [unioncollege-webtech/introduction#11]
The `npm test` script doesn't support ES6 syntax such as `let`, `const`, ~~and template literals~~. :cry: 

Edit: Here's my travis build error at the moment.

```
> introduction@1.0.0 test /home/travis/build/unioncollege-webtech/introduction
> node test
Hello! My name is Keith Wade. I'm 23 years old, and I am a Alumnus Computer Science major from Union College.
/home/travis/build/unioncollege-webtech/introduction/test/index.js:11
    assert(name, "The variable `name` doesn't exist. See 'Declaring Variables' under resources.");
          ^
ReferenceError: name is not defined
    at /home/travis/build/unioncollege-webtech/introduction/test/index.js:11:12
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
npm ERR! Test failed.  See above for more details.
```

**Comment by jgimbel** [comment]
Actually, it only doesn't support `let` and `const` because if block scoping. String template is fine
